### ISSUE TITLE
totally cool that you did this, what did you use it for?

### ISSUE THREAD

**Issue by govpack** [jmandel/ucum.js#1]
@jmandel 
###### totally cool that you did this, what did you use it for?

any thoughts on a leaner extensible way to add in data flow, screen + css dimensions and positions, currency exchange, javascript dates, and the prices of different things, and get them serialized and converted to and from json?

i'm considering doing a units of measure thing in JS, any tips/thoughts or pointers to current work that might help me from falling too deep in the rabbit hole? i want to keep the numeric values separate from their units

thanks

**Comment by jmandel** [comment]
Thanks @govpack! I put this together for two main reasons:

1. To learn UCUM more thoroughly
2. To offer for the community building SMART on FHIR apps (e.g. as a more correct alternative to hard-coding unit conversions in health apps).

It sounds like you have a bunch of goals with respect to a new JS package for dealing with quantities. I haven't surveyed the space very deeply, so I don't have a ready-to-go set of recommendations there.
