### ISSUE TITLE
Prettyprint units

### ISSUE THREAD

**Issue by neothemachine** [jmandel/ucum.js#6]
I was wondering which part is missing in ucum.js to allow to write a library that can prettyprint ucum units in a specific format (e.g. ASCII, or MathML, LaTeX, ...) that were parsed by ucum.js. The result of `ucum.parse` is not really helpful since it doesn't correspond to the original format and doesn't contain any ordering of the unit parts. Any ideas?

**Comment by jmandel** [comment]
I'm not sure precisely what you're asking -- ucum.js isn't designed for formatting units, but I suppose you could use its `parse` function as the first stage in a two-step process of 1) parsing and 2) formatting units.
