### ISSUE TITLE
Add API docs, clarify what parse and canonicalize do

### ISSUE THREAD

**Issue by neothemachine** [jmandel/ucum.js#7]
It would be good to have some docs for the three functions `convert`/`parse`/`canonicalize` inside the README file. `convert` is obvious, but `parse` and `canonicalize` deserve some explanation.

It seems that `parse` gets rid of prefixes. Is that the only thing it does?

And `canonicalize`, does this have the effect of converting to the particular [base units](http://unitsofmeasure.org/ucum.html#section-Base-Units) used for defining all units in the [UCUM document](http://unitsofmeasure.org/ucum.html)? This would be m, s, g, rad, K, C, cd. I think it is important to clarify this, since UCUM says "The selection of base units and the particular order are not normative. Any other basis B' that generates an isomorphic group of units is conformant with The Unified Code for Units of Measure".

**Comment by jmandel** [comment]
Thanks @neothemachine ! Please see if https://github.com/jmandel/ucum.js/commit/d85e4d7b4dbffc215d875bc1ad3da1a32cc843ce helps !

**Comment by jmandel** [comment]
Thanks -- updated with https://github.com/jmandel/ucum.js/commit/218fdea344d04c93bfa697e3f7e6a9fb2b826a94
