### ISSUE TITLE
Clarify which normative variant is supported

### ISSUE THREAD

**Issue by neothemachine** [jmandel/ucum.js#8]
There is the case-sensitive and the case-insensitive variant of UCUM symbols. A simple test seems to show that ucum.js only supports the former. Is that correct? If yes, then this should be added to the README.

**Comment by jmandel** [comment]
That's correct. README updated in https://github.com/jmandel/ucum.js/commit/7074f093802eec60c21a4ed9fbc656bd5ed0be1e
